// Home page
import Head from "next/head";
import EventsList from "@/components/events/EventsList";
import { getFeaturedEvents } from "@/dummy-data";

export default function Home(props) {
  let { featuresEvents } = props;

  return (
    <>
    <Head>
      <title>Events App</title>
      <meta name="author" content="Sallam Rady"/>
      <meta name="description" content="Find a lot of great events that allow you to evolve.."/>
    </Head>
    <EventsList items={featuresEvents} />
    </>
  );
}

// Now page became generated by : Server Side Generation.
export async function getStaticProps() {
  return {
    props: {
      featuresEvents: getFeaturedEvents(),
    },
    revalidate:100
  };
}
