// Home page
import EventsList from "@/components/events/EventsList";
import { getFeaturedEvents } from "@/dummy-data";

export default function Home(props) {
  let { featuresEvents } = props;

  return (
    <>
      <EventsList items={featuresEvents} />
    </>
  );
}

// Now page became generated by : Server Side Generation.
export async function getStaticProps() {
  return {
    props: {
      featuresEvents: getFeaturedEvents(),
    },
    revalidate:100
  };
}
